### ISSUE TITLE
Update README regarding security

### ISSUE THREAD

**Issue by secworks** [AlanReviews/File-Encryption#1]
The encryption performed is a byte-for-byte XOR using the same byte (the key is a single byte long). This scrambling is trivial to crack. It can possobly be seen as a simplified example of a Caesar cipher (which is useful for educational purposes).

Please add a disclaimer that this program is not to be used for any real encryption and protection of files.

https://github.com/AlanReviews/File-Encryption/blob/700c8619136997727028c9f8b788bcbeccabd32b/fileEncryption.c#L42-L43

**Comment by AlanReviews** [comment]
Thank you.
